/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fit.ghibefil.darwinrun;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import org.jbox2d.common.Vec2;
import org.jbox2d.dynamics.Body;
import sun.security.krb5.Config;

/**
 *
 * @author ghibe
 */
public class RenderPanel extends javax.swing.JPanel {
    Body athlete;    
    
    /**
     * Creates new form RenderPanel
     */
    public RenderPanel() {
        initComponents();
    }
    
    @Override
    public void paint(Graphics g) {
        Rectangle rect = g.getClipBounds();
        g.clearRect(0, 0, rect.width, rect.height);
        if (athlete==null)
            return;
        
        g.setColor(Color.red);
        
        Vec2 pos = athlete.getPosition();
        int x = (int) (pos.x * 2f);
        int y = (int) (- pos.y * 2f);
//        int x = 10;
//        int y = 5;
        //System.out.printf("rendering to %d %d on win of size %d %d\n", x, y, rect.width, rect.height);
        g.fillRect(x,y, 10, 10);
        
    }
    
    public void setRunner(Body athlete) {
        this.athlete = athlete;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
